#!/usr/bin/env python3

import re
from html.parser import HTMLParser
from utils import source_files

code_tag = re.compile(r'^(```.*)$', re.MULTILINE)
# <tag params> or </tag> + handle multilines and html tags in a quote (line starting with >)
html_tag = re.compile(r'</?[a-z]+(\s>?.*?)?>', re.MULTILINE | re.DOTALL)

for f in source_files:
    content = f.read()
    parts = code_tag.split(content)
    code = False
    nparts = []
    for part in parts:
        if part.startswith('```'):
            code = not code
        if not code:
            part = html_tag.sub('', part)
        nparts.append(part)
    source_files.send(''.join(nparts))
